#!/bin/bash
OUTPUT_FILE="src/data_translations.vala"

echo "// This file is automatically generated. Do not edit." > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "namespace DataTranslations {" >> "$OUTPUT_FILE"
echo "    // These strings are extracted for translation" >> "$OUTPUT_FILE"
echo "    public void initialize_translations() {" >> "$OUTPUT_FILE"

# Extract descriptions from src/assets/categories (values only, skipping [header])
grep "=" src/assets/categories | grep -v "^\[" | cut -d= -f2- | while read -r line; do
    ESCAPED_LINE=$(echo "$line" | sed "s/\"/\\\\\"/g")
    echo "        _(\"$ESCAPED_LINE\");" >> "$OUTPUT_FILE"
done

# Extract descriptions from src/assets/licenses (values only, skipping [header])
grep "=" src/assets/licenses | grep -v "^\[" | cut -d= -f2- | while read -r line; do
    ESCAPED_LINE=$(echo "$line" | sed "s/\"/\\\\\"/g")
    echo "        _(\"$ESCAPED_LINE\");" >> "$OUTPUT_FILE"
done

# Extract descriptions from src/assets/preview_text (Keys only, skipping [header])
grep "=" src/assets/preview_text | grep -v "^\[" | cut -d= -f1 | while read -r line; do
    ESCAPED_LINE=$(echo "$line" | sed "s/\"/\\\\\"/g")
    echo "        _(\"$ESCAPED_LINE\");" >> "$OUTPUT_FILE"
done

echo "    }" >> "$OUTPUT_FILE"
echo "}" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
