// This file is automatically generated. Do not edit.

namespace DataTranslations {
    // These strings are extracted for translation
    public void initialize_translations() {
        _("Fonts without decorative strokes; clean and modern, commonly used for UI and body text.");
        _("Decorative fonts designed for headlines and large sizes, not suitable for long text.");
        _("Fonts with decorative strokes at the ends of letters; traditional and often used in print.");
        _("Fonts that mimic handwritten or cursive styles; informal and expressive.");
        _("Fonts where all characters have equal width; commonly used for code and terminals.");
        _("Symbol-based fonts containing pictograms or UI icons instead of letters.");
        _("Fonts that do not fit standard categories or are highly experimental or mixed-style.");
        _("Permissive licence allowing almost unrestricted use, modification, and distribution.");
        _("Free to use, modify, and distribute, with conditions: no selling and original licence must be included.");
        _("Permissive, requires attribution, notice of changes, and inclusion of NOTICE file. Modified code can use a different licence.");
        _("Permissive, requires attribution and licence file.");
        _("Permissive license allowing unrestricted use, modification, and distribution.");
        _("Permissive license allowing unrestricted use, modification, and distribution.");
        _("arabic");
        _("armenian");
        _("bengali");
        _("canadian-aboriginal");
        _("cherokee");
        _("cyrillic");
        _("cyrillic-ext");
        _("devanagari");
        _("ethiopic");
        _("georgian");
        _("greek");
        _("greek-ext");
        _("gujarati");
        _("gurmukhi");
        _("hebrew");
        _("japanese");
        _("kannada");
        _("khmer");
        _("korean");
        _("latin");
        _("latin-ext");
        _("malayalam");
        _("myanmar");
        _("oriya");
        _("sinhala");
        _("syriac");
        _("tamil");
        _("telugu");
        _("thai");
        _("tibetan");
        _("vietnamese");
    }
}
